language: php

dist: trusty

env:
  global:
    - COMPOSER_ROOT_VERSION=4.0.x-dev

matrix:
  include:
    - php: 7.1
      env:
        - DB=MYSQL
        - PHPUNIT_COVERAGE_TEST=1
        - RECIPE_VERSION=4.2.x-dev
    - php: 7.2
      env:
        - DB=MYSQL
        - PHPUNIT_COVERAGE_TEST=1
        - RECIPE_VERSION=4.2.x-dev
    - php: 7.3
      env:
        - DB=MYSQL
        - PHPUNIT_COVERAGE_TEST=1
        - RECIPE_VERSION=4.x-dev

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:"$RECIPE_VERSION"
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml tests/php; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
